project:
  type: website
  output-dir: docs

website:
  title: "MUSTAFA ASLAN"
  open-graph: true
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - href: learn/index.qmd
        text: LEARN

      - text: WORKSHOPS
        href: workshops/index.qmd

      - href: talks/index.qmd
        text: TALKS

      - href: CV/CV.qmd
        text: CV

    tools:
      - icon: envelope
        href: mailto:aslanm@cardiff.ac.uk
      - icon: github
        href: https://github.com/mustafaslanCoto
      - icon: linkedin
        href: https://www.linkedin.com/in/aslanmu/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

